### ISSUE TITLE
Update website link

### ISSUE THREAD

**Issue by xerus2000** [bherrmann7/Car-Cast#125]
Both the repo and the F-Droid entry point to different, nonfunctional links.
I would appreciate a feature-overview with screenshots in the README as well for such cases.

**Comment by bherrmann7** [comment]
I updated the README on Car-Cast repo, I have access to that.    I did a minimal update.    The new readme link has an tour with screenshots.

Not sure how to effect anything on F-Droid.   I' had never heard of it before.

**Comment by xerus2000** [comment]
Oh, the website doesn't work on Firefox. Hmm...

F-Droid is the most popular (afaik) Android store that features only open source apps. But I now found out how to submit a change request.

**Comment by bherrmann7** [comment]
Humm....  I tried it on firefox (on Ubuntu) and it worked fine.     What version of firefox and what OS?     The webpage should work everywhere.

Thanks for your feedback!

**Comment by licaon-kter** [comment]
http://jadn.com/cc/ - says
```
HTTP Status 404 - /cc/
type Status report
message /cc/
description The requested resource is not available.
Apache Tomcat/9.0.0.M17
```

**Comment by licaon-kter** [comment]
:+1: https://gitlab.com/fdroid/fdroiddata/-/commit/cc1c9d479e887267a7d40dbd69456b92ed072b4f
